### ISSUE TITLE
Versão desatualizada. Favor atualizar aplicativo.

### ISSUE THREAD

**Issue by ruiblaese** [bbarreto/sinesp-nodejs#12]
Olá,

Parece que problema retornou novamente: Versão desatualizada. Favor atualizar aplicativo.

será que não tem webservice que disponibiliza a chave?

`{ codigoRetorno: '7', mensagemRetorno: 'Versão desatualizada. Favor atualizar aplicativo.' }`

`<?xml version='1.0' encoding='UTF-8'?>      <v:Envelope xmlns:i="http://www.w3.org/2001/XMLSchema-instance"      xmlns:d="http://www.w3.org/2001/XMLSchema" xmlns:c="http://schemas.xmlsoap.org/soap/encoding/"      xmlns:v="http://schemas.xmlsoap.org/soap/envelope/">        <v:Header>          <b>motorola XT1635-02</b>          <c>ANDROID</c>          <d>7.0</d>          <e>4.1.5</e>          <f>192.168.0.100</f>          <g>fc2abf59b5ca907ef3b44697e1f9514950eb3455</g>          <h>0.0</h>          <i>0.0</i>          <k/>          <l>2018-02-06 12:02:58</l>          <m>8797e74f0d6eb7b1ff3dc114d4aa12d3</m>        </v:Header>        <v:Body>          <n0:getStatus xmlns:n0="http://soap.ws.placa.service.sinesp.serpro.gov.br/">            <a>MGW0324</a>          </n0:getStatus>        </v:Body>      </v:Envelope>`

**Comment by luciocorrea** [comment]
Tem, mas é pago.

**Comment by chapeupreto** [comment]
@ruiblaese Submeti um Pull Request com as atualizações necessárias.

**Comment by bbarreto** [comment]
@chapeupreto @ruiblaese PR fechado e versão 1.0.7 do módulo publicada no npm

**Comment by GralakCobra** [comment]
Qual o endereço de Download ?
