### ISSUE TITLE
Parabéns pela excelente iniciativa!

### ISSUE THREAD

**Issue by xereda** [bbarreto/sinesp-nodejs#15]
Olá Barreto, tudo bem?

Queria parabenizá-lo pelo excelente trabalho. Muito bom!

Tenho um questão: Por acaso, vc sabe se há disponível APIs públicas relativas as informações de veículos (DETRAN)?

Desde já agradeço seu retorno.

Um abraço,

**Comment by bbarreto** [comment]
Até o momento, o único fornecedor público de API é o SERPRO, mas não há nenhuma com dados sobre veículos até o momento.

O grande problema é o modelo de precificação, que obriga que você contrate um mínimo mensal, indo na contramão do mercado que cobra somente pelo uso.

https://servicos.serpro.gov.br/api-serpro/
