### ISSUE TITLE
Versão desatualizada. Favor atualizar aplicativo.

### ISSUE THREAD

**Issue by MagnusIIIBR** [bbarreto/sinesp-nodejs#16]
Aparentemente voltou a dar erro por conta de alguma atualização do SINESP referente a versão do app.

![image](https://user-images.githubusercontent.com/9530663/42331674-687d4604-804c-11e8-9c49-eecb73a83f75.png)

**Comment by bbarreto** [comment]
@MagnusIIIBR realmente está com esse problema. O app do sinesp foi atualizado na segunda-feira mas ainda não tive tempo de avaliar as mudanças. Pelo pouco que vi, eles migraram para a api v5.

O projeto está aberto para receber pull requests com a correção. Assim que for resolvido, farei a atualização do repositório e da versão no npm.

**Comment by armmmo** [comment]
Tambem esperando pela atualização

**Comment by bbarreto** [comment]
Problema resolvido no pull request #17
