### ISSUE TITLE
Versão desatualizada

### ISSUE THREAD

**Issue by oluizfabio** [bbarreto/sinesp-nodejs#9]
Mensagem versão desatualizada, favor atualizar o aplicativo na consulta.

**Comment by igtoth** [comment]
Como faz para pegar o token novo?

**Comment by bbarreto** [comment]
Parece que o SINESP implementou um captcha na chamada. Estou fazendo a engenharia reversa do código para entender como quebrar.

**Comment by giovanigenerali** [comment]
@bbarreto abri o apk aqui, não entendi bulhufas... só vi que trocaram o host ```http://cidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v2``` e a versão ```4.3```.

**Comment by igtoth** [comment]
@bbarreto não tinha captcha antes ?

**Comment by gregserrao** [comment]
pessoal, parace que mudou somente um token eu fiz um sniffer no app android e coloquei mesmo xml da requisição fixo nesse código e funcionou, acontece que o hash gerado não está batendo com o servidor.

**Comment by gregserrao** [comment]
@bbarreto cara em que parte do código do app que vc encontrava o secret?
Eu fiz a engenharia reversa dessa nova versão, mas não consegui encontrar isso.

**Comment by oluizfabio** [comment]
@gregperes pelo que eu entendi da galera do discord não foi exatamente o secret que mudou e sim a lib onde ele gera o hash, agora estão tentando descobrir se foi alterado o algoritmo ou foi adicionado mais alguma chave no processo.

**Comment by bbarreto** [comment]
@oliveirafabio parece que a geração do novo secret é dinâmica, mas não consegui decifrar ainda como faz

@gregperes antes dava pra achar o secret só monitorando a comunicação de rede do aplicativo, pegando do XML que ele enviava pro serviço

**Comment by gregserrao** [comment]
@oliveirafabio entendi cara, fiz a engenharia reversa da lib que gerar isso mas não consegui entender o código.

@bbarreto saquei cara, pq olhando os fontes do app, parece que ele usa uma lib nativa chamada lib-superplacas eu consegui fazer a engenharia reversa dessa lib, mas como eu não manjo de C eu não entendi muita coisa, mas se eu puder ajudar em algo contem comigo :)

**Comment by Kkshi28** [comment]
aqui deixo (por se é mais fácil fazer essa engenharia reversa em outras app) uns link para baixar as apk de outras app que se atualizaram e já estão mostrando os dados das placas

https://apkpure.com/br/consultar-placa-detran/br.com.jeronimo.checaplacas 
https://apkpure.com/br/consulta-placa-e-tabela-fipe/br.com.samuelfreitas.consultarplaca.app 
https://apkpure.com/br/consulta-placa-e-tabela-fipe/br.com.app4br.consultaplaca.app 
https://apkpure.com/br/consulta-placa-e-tabela-fipe/br.com.app4br.consultaplaca.app 
https://apkpure.com/br/consulta-placa-e-tabela-fipe/br.com.appsfacil.consultaplaca.app 
https://apkpure.com/br/consulta-placa-e-fipe/br.com.mobills.consultaplaca

**Comment by Kkshi28** [comment]
Em android somente tive que sobrescrever as lib-superplacas.so nativas das apps que funcionavam foi o único que atualizaram todo segue igual da vez anterior

**Comment by luciocorrea** [comment]
@Kkshi28 Não querendo fazer alarde, mas dessa forma você estará usando o código do SERPRO. E na lib tem uma mensagem bem grande sobre copyright. 

Mas aí vai de cada um analisar se vale a pena correr o risco.

**Comment by Kkshi28** [comment]
Opa o app que atualizei é só para meu consumo de teste para outro serviço que tenho meu interesse em realidade aqui é este modulo de node que o que utilizo em uma parte de meu serviço, mas não tenho a capacidade para resolver o problema em node, só deixei a ideia por se dava alguma solução para vocês 
;)

**Comment by luciocorrea** [comment]
@Kkshi28 Eu já solucionei o problema sem usar a lib.

**Comment by Kkshi28** [comment]
Atualiza aqui então kkkkk

**Comment by Kkshi28** [comment]
mas em node o em uma app ?? me interessa que seja uma solução para node como este modulo por exemplo

**Comment by bbarreto** [comment]
@luciocorrea se não tiver em node, pode enviar o código na linguagem que você escreveu e eu subo a mudança no módulo ainda hoje

**Comment by gregserrao** [comment]
@luciocorrea compartilha a sua solução :)

**Comment by luciocorrea** [comment]
Não quero polemizar. Mas se alguém usa a API comercialmente (não especificamente esse projeto do @bbarreto ) e quiser consultoria pra fazer funcionar, é só me procurar  no Telegram: luciocorrea

**Comment by higordiego** [comment]
@bbarreto, estou precisando da solução, pode auxiliar ?

**Comment by rafaelgasparini** [comment]
Opa eae galera td certo? estou usando aqui mas esta me retornando { codigoRetorno: '7',
  mensagemRetorno: 'Versão desatualizada. Favor atualizar aplicativo.' } alguem pode me ajudar?

**Comment by giovanigenerali** [comment]
@bbarreto a alteração do @oliveirafabio funcionou. Quando puder fazer o aceite do pull request, agradeço!

**Comment by bbarreto** [comment]
Estou chegando no escritório e já vejo 🙃

enviado pelo celular

Em 31 de jan de 2018 10:23, "Giovani Generali" <notifications@github.com>
escreveu:

**Comment by bbarreto** [comment]
Merge feito e versão 1.0.6 publicada no npmjs https://www.npmjs.com/package/sinesp-nodejs
